fix: starts-with should be able to handle null/undefined input
asd-xiv/m pull request #22
Opened 2022-08-25 08:59 UTC by dgilperez

## Primary

1. Fix bug in starts-with when null/undefined input is provided

## Checklist

- [x] Tests
- [ ] JSDocs
- [x] Export in `src/index.js`

2022-08-25 09:01 UTC, dgilperez commented
@andreidmt this should be a no brainer and a quick fix, if you could fast-track this one you'd save me a bit of a headache ... :)

2022-08-25 09:31 UTC, andreidmt requested changes
Thanks for this! :+1: 

About `startsWith`, please also add a test checking the for `Object` input:

```js
t.equals(
  startsWith("lorem")({ lorem: "lorem" }),
  false,
  "Search in Object should returns false"
)
```

... and about the implementation, this should be a bit less verbose and should work in all cases:

```js
const _startsWith = (search, input) => {
  if (typeof input === "string" || Array.isArray(input)) {
    return input.indexOf(search) === 0
  }

  return false
}
```

2022-08-25 10:05 UTC, andreidmt commented
I have a major PR with packages updates, some CI changes and node 18 support but I'll push that after we merge this one.

2022-08-29 05:56 UTC, andreidmt commented
@dgilperez I added you as a contrib to `m` as well. You can be a reviewer and can make PRs where I can also push changes.

Also take a look at #23 , hopefully you dont have any v14 cloud functions anymore.

2022-08-31 08:38 UTC, dgilperez commented
Thanks a lot @andreidmt !! sorry for the silence, I'm on a retreat mostly offline - I will get back on a couple of days!

2022-09-01 09:33 UTC, dgilperez commented
Ready to check again @andreidmt :)

2022-09-07 10:27 UTC, andreidmt approved these changes
Go for it! :+1:

2022-09-07 11:27 UTC, dgilperez commented
Super! Before merging ( 😊 ):
Just to confirm: "rebase and merge", right? Anything else needed before merging or semantic release will take care of everything?

2022-09-07 14:04 UTC, andreidmt commented
> Super! Before merging ( blush ): Just to confirm: "rebase and merge", right? Anything else needed before merging or semantic release will take care of everything?

Always "Squash and Merge" from the GitHub interface (i've disabled other types anyway). If you want to do it from the terminal, it's [a bit longer](https://gist.github.com/aortbals/2aeb557bf127dd7ae88ea63da93479fc#take-2-git-squashed-merge)

The CI pipeline will take care of Linting, Testing, Test Coverage submission and Versioning + NPM publishing.

Hit it! :rocket:

2022-09-07 14:09 UTC, merged

2022-09-07 14:09 UTC, dgilperez commented
🍻

2022-09-07 18:53 UTC, dgilperez commented
hmm so it seems the release to npm failed, @andreidmt ? any idea why?

2022-09-08 07:46 UTC, andreidmt commented
@dgilperez yeah, there was a commitlint error. Fixed it and it the ver got deployed

https://app.circleci.com/pipelines/github/asd-xiv/m/293/workflows/e19fc62c-2719-4a88-8723-ad9aafc095ac/jobs/658

2022-09-08 10:10 UTC, dgilperez commented
Oh, I see it now, thanks. 

Any reason for the github releases not be created / updated? Latest is 7.7.1 from January

2022-09-08 10:11 UTC, andreidmt commented
Indeed, that shouldnt happen. Ill take a look today.

2022-09-14 12:07 UTC, andreidmt commented
> Any reason for the github releases not be created / updated? Latest is 7.7.1 from January

@dgilperez Fixed it in the #23. For some reason the Semantic Release plugin for GitHub was missing. Also switched to [Conventional Commits](https://www.conventionalcommits.org) from the default [Angular](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit).

I always write CC messages thinking it's the default for [semantic-release](https://github.com/semantic-release/semantic-release#commit-message-format) ... but it's actually Angular :laughing:.

Realized when pushing a `feat!: major upgrades` on `asd14/eslint-config` and expecting a major version bump but Angular fully ignores the commit.