Improve spy output
asd-xiv/m pull request #4
Opened 2021-03-25 21:54 UTC by dgilperez

spy is not very useful for long collections or objects when passed through a `JSON.stringify`, removing it for those two.

2021-03-27 11:12 UTC, andreidmt commented
Yes, `spy` is not very useful right now but I would go a different direction:

- A more verbose value output using `JSON.stringify(spyValue, null, 2)`, this would printout indented object and arrays with 2 spaces
- Ability to slice the data before outputing

```js
const input = [{ id: 1 }, { id: 2 }, { id: "uuid" }]

pipe(
  updateMany({ foo: "bar" }),
  spy({
    description: "First 2 items",
    transform: top(2),
  }),
  // // First 2 items
  //
  // [
  //  {
  //    "id": 1,
  //    "foo": "bar"
  //  },
  //  {
  //    "id": 2,
  //    "foo": "bar"
  //  }
  // ]

  updateMany({ lorem: "ipsum" }),
  spy()
  // // @asd14/m/spy
  //
  // [
  //   {
  //     "id": 1,
  //     "foo": "bar",
  //     "lorem": "ipsum"
  //   },
  //   {
  //     "id": 2,
  //     "foo": "bar",
  //     "lorem": "ipsum"
  //   },
  //   {
  //     "id": "uuid",
  //     "foo": "bar",
  //     "lorem": "ipsum"
  //   }
  // ]
)(input)
```

Would look like:

```js
const spy = (props = {}) => (...source) => {
  if (source.length > 1) {
    throw new Error(
      `@asd14/m/spy - Can only be called with 1 parameter, received ${source.length}`
    )
  }

  const { description = "@asd14/m/spy", transform } = props
  const hasTransform = is(transform)
  const spyValue = hasTransform ? transform(source[0]) : source[0]

  console.log()
  console.log(`// ${description}`)
  console.log()

  console.log(JSON.stringify(spyValue, null, 2))

  // Make sure we're just proxying input, not creating another instace etc
  return source[0]
}
```

2021-03-28 14:37 UTC, dgilperez commented
Interesting, thanks! Let's see if this is ok now - tests are green.

2021-03-28 15:24 UTC, andreidmt requested changes
Cool, looks good! Ignore the `.dccache` and it's ready.

2021-03-28 15:24 UTC, andreidmt commented on .dccache
> +[{"/Users/dgilperez/src/holarosita/dependencies/m/docs/index.html":"1","/Users/dgilperez/src/holarosita/dependencies/m/src/index.js":"2","/Users/dgilperez/src/holarosita/dependencies/m/src/index.test
Please add this to .gitignore

2021-03-28 19:18 UTC, dgilperez commented
Ups! Done

2021-03-28 19:23 UTC, merged

2021-03-28 19:55 UTC, andreidmt commented
:tada: This PR is included in version 5.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@asd14/m/v/5.3.0)
- [GitHub release](https://github.com/asd-xiv/m/releases/tag/v5.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-03-28 20:28 UTC, dgilperez commented
Thanks! 🍻